"""The data-intake page must make an absence and a provenance visible.

Every finding this page exists for is a value of the right shape arriving from
somewhere other than where its consumers assume. None of them raises, so none
can be tested by asserting "no exception" — these assert the page *says so*.
"""
from __future__ import annotations

import os
from contextlib import contextmanager

os.environ.setdefault("OPS_SESSION_SECRET", "test")
os.environ.setdefault("OPS_AUTH_TOKEN", "test-token")


def _report(**over):
    """The engine's real payload shape.

    Mirrors ``src/data_intake.build_data_intake``'s output rather than a shape
    invented here — a fixture whose keys you chose asserts your assumption back
    at you and goes green over a page that cannot render.
    """
    base = {
        "schema": 1,
        "generated_at": 1_700_000_000.0,
        "pools": [
            {
                "label": "futures_klines", "present": True, "state": "healthy",
                "streams_total": 2, "degraded_count": 0,
                "connections": [{
                    "index": 0, "streams": 2, "silent_streams": 0,
                    "silent_sample": [], "degraded": False,
                    "reconnect_attempts": 0, "ping_latency_ms": 11.0,
                    "last_reconnect_ms": 0.0, "connected_age_s": 120.0,
                    "seconds_to_forced_cycle": 86_280.0,
                    "msgs_since_health_check": 500,
                }],
            },
            {
                "label": "spot", "present": False, "state": "not_started",
                "streams_total": 0, "degraded_count": 0, "connections": [],
            },
        ],
        "stream_kinds": {
            "distinct_stream_suffixes": ["!ticker@arr", "@forceOrder", "@kline_1m"],
            "kinds": {
                "klines": True, "liquidations": True, "all_market_ticker": True,
                "aggregate_trades": False, "raw_trades": False, "depth": False,
            },
        },
        "series": {
            "present": True, "symbols_sampled": 1, "symbols_total": 1,
            "symbols_in_scan_universe": 1,
            "symbols_retained_outside_universe": 0,
            "by_timeframe": {
                "1m": {
                    "series": 2, "stale": 1, "undated": 1,
                    "series_scanned": 1, "stale_scanned": 1, "undated_scanned": 0,
                    "bars_min": 10, "bars_max": 500,
                    "oldest_newest_bar_age_s": 3600.0, "stale_budget_s": 180.0,
                    "stalest_symbols": [{"symbol": "BTCUSDT", "age_s": 3600.0}],
                },
            },
        },
        "derived": {
            "cvd": {"source": "kline_taker_buy",
                    "detail": "closed 1m/15m kline Q/q fields — not tick data",
                    "symbols_tracked": 75, "symbols_tracked_15m": 75},
            "ticks": {"source": "rest_seed_snapshot",
                      "detail": "/fapi/v1/trades limit=1000 at seed time; no "
                                "@trade or @aggTrade subscription feeds it",
                      "symbols": 75, "rows": 75_000,
                      "newest_trade_age_s": 14_400.0,
                      "consumers": ["scanner._build_scan_context (recent_ticks)"]},
            "order_book": {"source": "book_ticker", "quality": "top_of_book_only",
                           "detail": "one bid and one ask", "symbols_cached": 75},
            # Phase 2c. Generated by driving the engine's own `_depth_report()`
            # (360-v2 `src/data_intake.py`) rather than written from the
            # template's needs — a fixture whose keys the reader chose is the
            # `zone_distance_atr` failure, where two tests passed for months on
            # a shape nothing had ever produced.
            "depth": {
                "present": True,
                "levels": 20,
                "speed_ms": 500,
                "stale_after_s": 10.0,
                "symbols_known": 3,
                "symbols_subscribed": 3,
                "delivering": 2,
                "stale": 0,
                "never_delivered": 1,
                "thin_books": 2,
                "messages_total": 2,
                "messages_rejected": 0,
                "oldest_book_age_s": 0.005,
                "stale_symbols": [],
                "never_symbols": ["NOPEUSDT"],
                "measurement_enabled": True,
                "live_for_consumers": False,
                "comparison": {
                    "n": 2,
                    "sign_flips": 1,
                    "mean_abs_delta": 0.7387712640473856,
                    "rows": [
                        {"symbol": "BTCUSDT", "imb_top1": 0.8165304268846503,
                         "imb_topn": -0.6511111111111111,
                         "delta": -1.4676415379957612, "sign_flip": True,
                         "levels_used": 2, "levels_held": 2},
                        {"symbol": "ETHUSDT", "imb_top1": -0.009900990099009901,
                         "imb_topn": -0.019801980198019802,
                         "delta": -0.009900990099009901, "sign_flip": False,
                         "levels_used": 2, "levels_held": 2},
                    ],
                },
            },
            # Phase 5. Generated by driving the engine's own
            # `_price_action_lane_report()` (360-v2 `src/data_intake.py`) with a
            # populated census, then pasting its output — not written from what this
            # template happens to need. The whole reason this block is here is that
            # the fixture above is a hand-maintained mirror of the engine payload and
            # was therefore silent by construction on the key the engine started
            # sending on 2026-08-06.
            "price_action_lane": {
                "present": True,
                "measure_enabled": True,
                "evaluated": 4210,
                "emitted": 3,
                "refusals": {
                    "no_sweep": 3620, "no_footprint": 402, "delta_opposed": 131,
                    "rr_below_floor": 34, "cooldown": 12, "no_levels": 8,
                },
                "refusal_share": {
                    "no_sweep": 0.8598574821852731,
                    "no_footprint": 0.09548693586698337,
                    "delta_opposed": 0.03111638954869359,
                    "rr_below_floor": 0.008076009501187649,
                    "cooldown": 0.0028503562945368173,
                    "no_levels": 0.0019002375296912114,
                },
            },
            "open_interest": {"source": "rest_poll", "symbols": 75},
            "funding": {"source": "rest_poll", "symbols": 75},
            "liquidations": {"source": "ws_force_order", "symbols": 75},
        },
        "primitives": {"rows": [
            {"primitive": "orderblocks", "status": "not_implemented",
             "healthy": False,
             "detail": "declared on SMCResult and never assigned — every "
                       "`bool(fvgs) or bool(orderblocks)` gate is `bool(fvgs)` alone"},
            {"primitive": "fvg", "status": "lookback=10", "healthy": True,
             "detail": "sees ~12 bars — on 15m that is ~3.0h of structure"},
        ]},
        "levels": {
            "level_book": {"present": True, "symbols": 75, "levels_total": 900,
                           "oldest_refresh_age_s": 42.0},
            "volume_profile": {
                "micro": {"symbols": 75, "state": "ok"},
                "macro": {"symbols": 0, "state": "unreadable: no _results attribute"},
            },
        },
        "footprint": {
            "present": True, "symbols": 40, "open_bars": 40,
            "sealed_bars": 2_400, "bins_held": 41_000,
            "incomplete_bars_held": 3, "capped_bars_total": 1,
            "incomplete_bars_total": 5, "bar_ms": 60_000, "bin_bps": 5.0,
            "bars_per_symbol": 120, "max_bins_per_bar": 400, "uptime_s": 3_600.0,
            "sample": {
                "symbol": "BTCUSDT", "bar_open": 1_700_000_000_000,
                "bin_bps": 5.0, "anchor": 50_000.0,
                "buy_quote": 1_250_000.0, "sell_quote": 900_000.0,
                "delta_quote": 350_000.0, "total_quote": 2_150_000.0,
                "trades": 4_120, "bins": 38, "bins_capped": False,
                "incomplete": False, "incomplete_reason": "",
                "range_pct": 0.184, "poc_price": 50_025.0, "poc_quote": 310_000.0,
                "size_buckets": {"<100": 900, "100-1k": 2_100, "1k-10k": 950,
                                 "10k-100k": 160, ">100k": 10},
                "max_imbalance": {"bin": 5, "price": 50_012.5, "ratio": 4.2,
                                  "one_sided": False, "side": "BUY",
                                  "quote": 180_000.0, "min_quote_floor": 0.0},
                "cvd_quote_60": 1_400_000.0,
                "volume_baseline_30": 1_900_000.0,
            },
        },
        "live_ticks": {
            "present": True, "stream_enabled": True, "max_symbols": 40,
            "subscribed": 40, "fed": 38, "quiet": 1, "subscribed_silent": 1,
            "subscribed_silent_sample": ["NOPEUSDT"], "quiet_sample": [],
            "rows": 38_000, "total_accepted": 120_000, "total_rejected": 0,
            "uptime_s": 900.0, "maxlen": 1000, "quiet_after_s": 90.0,
            "serving_consumers": False,
            "drift_vs_seeded": {
                "compared": 30, "median_gap_s": 3_600.0,
                "worst": [{"symbol": "BTCUSDT", "seeded_age_s": 14400.0,
                           "live_age_s": 0.4, "gap_s": 14399.6}],
            },
        },
        "weight": {
            "futures": {"used": 300, "budget": 2200, "pct": 13.6},
            "spot": {"used": 10, "budget": 5500, "pct": 0.2},
            "declared": {
                "/fapi/v1/trades": {"weight": 5, "source": "verified:2026-08-05",
                                    "note": "Recent Trades List"},
                "/fapi/v1/klines": {"weight": -1, "source": "carried",
                                    "note": "weight varies by limit"},
            },
        },
    }
    base.update(over)
    return base


@contextmanager
def _client(payload=None, raises=None):
    from fastapi.testclient import TestClient

    from app.main import app

    class _API:
        async def data_intake(self):
            if raises is not None:
                raise raises
            return payload

        async def aclose(self):
            pass

    with TestClient(app) as client:
        client.post("/login", data={"password": os.environ["OPS_AUTH_TOKEN"]},
                    follow_redirects=False)
        app.state.engine_api = _API()
        yield client


class TestTheAbsencePanel:
    def test_an_unsubscribed_stream_kind_is_named_not_omitted(self):
        """An absence cannot be seen in a list of what is present. That is
        exactly how a missing trade stream sat behind a complete, unreachable
        handler in main.py."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Aggregate trades" in body
        assert "Raw trades" in body
        assert "Order book depth" in body
        assert "NOT SUBSCRIBED" in body

    def test_the_page_says_what_each_absence_costs(self):
        """A row reading 'not subscribed' is a fact. The consequence is what
        makes it actionable."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "no footprint" in body
        assert "one bid and one ask" in body

    def test_a_subscribed_kind_renders_as_subscribed(self):
        r = _report()
        r["stream_kinds"]["kinds"]["aggregate_trades"] = True
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "SUBSCRIBED" in body


class TestProvenance:
    def test_the_tick_store_is_badged_not_live(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "rest_seed_snapshot" in body
        assert "not live" in body

    def test_a_stale_tick_store_shows_its_age_prominently(self):
        """4h old, on a store five call sites read as current."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "240m old" in body

    def test_the_consumers_of_the_stale_store_are_named(self):
        """Named because the risk is theirs."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "_build_scan_context" in body

    def test_cvd_source_is_shown_rather_than_implied(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "kline_taker_buy" in body
        assert "not tick data" in body

    def test_the_order_book_quality_is_badged(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "top_of_book_only" in body


class TestTheCensusRendersUnconditionally:
    def test_a_hollow_primitive_is_shown_with_its_cause(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "not_implemented" in body
        assert "no writer" in body

    def test_the_census_renders_when_everything_is_healthy(self):
        """A check that appears only when it trips teaches the reader that its
        absence means 'fine' when it equally means the check stopped running."""
        r = _report()
        r["primitives"]["rows"] = [
            {"primitive": "orderblocks", "status": "live", "healthy": True,
             "detail": ""},
        ]
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Structural primitives" in body
        assert "orderblocks" in body


class TestPools:
    def test_a_never_started_pool_is_named_not_shown_as_zero(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "NOT STARTED" in body

    def test_the_24h_forced_cycle_countdown_renders(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "To 24h cycle" in body
        assert "24.0h" in body


class TestSeries:
    def test_undated_is_a_separate_column_from_stale(self):
        """Different faults, different fixes — pooling them reports the wrong
        one."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Undated" in body and "Stale" in body

    def test_each_timeframe_shows_its_own_budget(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "180s" in body  # the 1m budget, beside the age


class TestWeight:
    def test_the_live_gauge_renders(self):
        """The header value had been synced into the limiter and never
        rendered anywhere."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "300 / 2200" in body

    def test_the_declared_table_shows_provenance_per_entry(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "verified:2026-08-05" in body
        assert "carried" in body
        assert "not thereby confirmed" in body


class TestFailureIsNotEmptiness:
    def test_an_unreachable_engine_renders_a_cause(self):
        """An empty page here reads exactly like an engine with nothing
        subscribed — the one conclusion this page must never allow by
        accident."""
        with _client(raises=RuntimeError("connection refused")) as c:
            resp = c.get("/diagnostics/data-intake")
        assert resp.status_code == 200
        assert "Cannot read the intake report" in resp.text
        assert "connection refused" in resp.text

    def test_an_engine_side_error_payload_is_surfaced(self):
        with _client({"schema": 0, "error": "RuntimeError: boom"}) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "engine reported" in body and "boom" in body

    def test_an_unexpected_shape_does_not_crash_the_page(self):
        """The engine REST surface is the source of truth and this dashboard
        adapts to it rather than crashing on drift."""
        with _client(["not", "a", "dict"]) as c:
            resp = c.get("/diagnostics/data-intake")
        assert resp.status_code == 200
        assert "unexpected payload shape" in resp.text


class TestWiring:
    def test_the_page_is_in_the_nav(self):
        """A page reachable only by typing its URL is 'measured but nowhere to
        look' one step removed."""
        from pathlib import Path
        base = Path(__file__).resolve().parents[1] / "app/templates/base.html"
        assert "/diagnostics/data-intake" in base.read_text()

    def test_the_route_is_registered(self):
        from app.main import app
        assert any(
            getattr(r, "path", "") == "/diagnostics/data-intake" for r in app.routes
        )


class TestLiveTickPanel:
    """Phase 2a shipped its engine payload and NO ops surface — the panel below
    did not exist, so the drift measurement its handover flag waits on had
    nowhere to be read. "A dark change ships together with the ops surface that
    shows what it is doing" is the rule, and this is it."""

    def test_the_panel_renders(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Live aggressive trades" in body

    def test_the_handover_flag_is_shown_as_a_flag_not_as_health(self):
        """A working feed is not a reason to change what a live gate sees."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "SEED SNAPSHOT" in body
        assert "TICKS_LIVE_FOR_CONSUMERS" in body

    def test_the_handover_reads_differently_once_flipped(self):
        r = _report()
        r["live_ticks"]["serving_consumers"] = True
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "LIVE SERIES" in body

    def test_the_drift_measurement_is_on_screen(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Drift against the seeded store" in body
        assert "60 min" in body   # median gap, badged

    def test_a_subscription_that_never_delivered_is_named(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "never delivered" in body and "NOPEUSDT" in body

    def test_the_uptime_caveat_is_stated(self):
        """The seed snapshot is freshest right after a restart, so a page read
        minutes after a deploy understates the very error it is sizing."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "function of" in body and "uptime" in body


class TestReportedFaultsThatAreNotHappening:
    def test_a_pool_whose_silence_is_expected_says_so(self):
        r = _report()
        r["pools"][0]["silence_is_expected"] = True
        r["pools"][0]["silence_budget_s"] = 12_000.0
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "silence expected on this pool" in body

    def test_stale_leads_with_the_scanned_count(self):
        """A rotated-out mover's bucket freezes by design. Pooling it with a
        core pair reports a real fault at several times its true size."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "scanned / all" in body
        assert "in the live scan universe" in body

    def test_an_unreadable_volume_profile_is_not_rendered_as_zero(self):
        """An all-zero column is a claim about the reader before it is a claim
        about the system — a guessed attribute name returns an empty dict just
        as convincingly for "empty" as for "wrong name"."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "unreadable: no _results attribute" in body


class TestFootprintPanel:
    """Phase 2b's ops surface. A data layer with nowhere to look is an
    unfinished change, and this one carries the distinction the whole phase
    exists for: magnitudes, never verdicts."""

    def test_the_panel_renders_with_a_real_bar(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Footprint — volume at price" in body
        assert "Newest sealed bar" in body and "BTCUSDT" in body

    def test_it_says_what_the_single_per_bar_delta_cannot(self):
        """The reason the layer exists, on screen — otherwise a reader sees a
        second CVD and assumes duplication."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "one signed number per" in body
        assert "structurally silent" in body

    def test_no_verdict_language_appears(self):
        """A boolean bakes in a threshold nobody has earned. The page states
        ratios and components."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Magnitudes, never verdicts" in body
        assert "4.2:1 BUY" in body

    def test_a_one_sided_level_is_badged_not_printed_as_a_big_ratio(self):
        """'Nobody sold here at all' is a different observation from 'a big
        ratio', so it is not rendered as one."""
        r = _report()
        r["footprint"]["sample"]["max_imbalance"] = {
            "bin": 5, "price": 50_012.5, "ratio": None, "one_sided": True,
            "side": "BUY", "quote": 180_000.0, "min_quote_floor": 0.0,
        }
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "BUY only" in body
        assert "no opposing volume at all" in body

    def test_capped_and_incomplete_bars_are_badged_with_their_meaning(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "shape-capped" in body
        assert "EXACT totals" in body
        assert "carries its cause" in body

    def test_the_relative_grid_is_explained(self):
        """An absolute grid is 20% wide on a sub-cent mover — every cheap
        symbol would collapse into one bin and read perfectly balanced."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "5.0 bps bins" in body
        assert "never an absolute" in body

    def test_the_tick_cvd_is_labelled_a_detector_not_a_duplicate(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "detector" in body and "duplicate" in body

    def test_an_empty_store_renders_its_counts_and_says_why(self):
        """Distinguishable from a stalled store by the coverage counts, which
        is exactly why they render whether or not a sample exists."""
        r = _report()
        r["footprint"]["sample"] = None
        r["footprint"]["sealed_bars"] = 0
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "No sealed bar yet" in body
        assert "expected state for the first minute" in body


class TestDepthPanel:
    """Phase 2c — the real book, and the handover it is waiting on.

    The panel exists because the engine change is dark: four consumers (the OBI
    execution gate, `book_imbalance`, the WHALE OBI check, the AI predictor)
    keep reading a one-level bookTicker snapshot until the measured
    disagreement has been read. "Measured but nowhere to look" is an unfinished
    change, and this is the place to look.
    """

    def test_the_panel_renders(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Order-book depth" in body

    def test_subscribed_is_not_consumed(self):
        """The defect this panel is most able to cause. A healthy depth feed
        rendered without the handover state reads as though the book were in
        use — and it is not."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "MEASURING ONLY" in body
        assert "one-level bookTicker" in body
        assert "Nothing on this card affects a signal." in body

    def test_the_handover_reads_differently_once_flipped(self):
        r = _report()
        r["derived"]["depth"]["live_for_consumers"] = True
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "LIVE FOR CONSUMERS" in body
        assert "MEASURING ONLY" not in body

    def test_the_disagreement_is_the_headline_measurement(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Does depth change the picture?" in body
        assert "same snapshot" in body
        # The sign flip is what a directional consumer is harmed by.
        assert "Sign flips" in body
        assert "1 of 2" in body

    def test_the_denominator_is_what_we_subscribed(self):
        """A feed that dies leaves its snapshots behind, so a count of what the
        store HOLDS reads healthy while nothing arrives (#815's shape)."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "2 / 3 books fresh" in body
        assert "never delivered" in body and "NOPEUSDT" in body

    def test_silence_is_named_a_fault_on_this_stream_and_not_on_aggtrade(self):
        """The two feeds are graded on different clocks and the page says why —
        otherwise a reader carries aggTrade's 90s quiet budget across."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "fixed clock" in body
        assert "never a quiet market" in body

    def test_a_thin_book_reports_the_levels_it_actually_held(self):
        """A 3-level answer labelled 20 is the mislabelling this lane exists to
        stop."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "of 20" in body          # levels_used < levels, named on the row
        assert "Thin books" in body

    def test_an_empty_comparison_says_why_rather_than_rendering_blank(self):
        """"Blank needs a cause before it gets a caption" — an empty table and
        a stalled feed must not read alike."""
        r = _report()
        r["derived"]["depth"]["comparison"] = {
            "n": 0, "rows": [], "sign_flips": 0, "mean_abs_delta": None,
        }
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "No fresh book has produced a comparison yet" in body
        # ...and the coverage counts still render, so the reader can tell the
        # two states apart.
        assert "2 / 3 books fresh" in body

    def test_an_unreadable_depth_report_is_named_not_hidden(self):
        r = _report()
        r["derived"]["depth"] = {"present": False, "error": "boom"}
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "UNREADABLE" in body and "boom" in body


class TestThePriceActionLaneCensus:
    """The engine wrote `price_action_lane` into the payload on 2026-08-06 and
    this page rendered nothing for it, so the owner asked "why is price action
    still not generating signals" against a page that had the answer and did not
    show it.

    That is #817 inverted — a field one repo *writes* and no repo *reads* — and
    it survived because the producing side's test asserted the engine function's
    own return shape, which is a mock asserting your assumption back at you one
    repo short of the reader. These assert the PAGE says it.
    """

    def test_the_refusal_mix_renders_with_its_shares(self):
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Price-action lane" in body
        # Every reason the engine sent is on the page, not just the top one.
        for reason in ("no_sweep", "no_footprint", "delta_opposed",
                       "rr_below_floor", "cooldown", "no_levels"):
            assert reason in body, reason
        assert "86.0%" in body      # no_sweep share
        assert "9.5%" in body       # no_footprint share

    def test_the_denominator_is_evaluations_and_says_so(self):
        """Dividing refusals by emissions would put a rare-by-design numerator
        under a rare-by-design denominator."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "4210" in body
        assert "denominator for every share" in body

    def test_emission_is_not_presented_as_the_health_signal(self):
        """The trigger is rare by design, so zero rows is a quiet market. A page
        that reads three stamped rows as a fault teaches the owner to ignore it."""
        with _client(_report()) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "Emission is not the health signal" in body

    def test_a_reason_ops_has_no_sentence_for_is_named_not_dropped(self):
        """The classification here is COPY, not a mirror of the engine's reason
        list. A reason ops has never heard of must appear under its own name —
        the `MEASUREMENT_SUFFIXES` drift is what a silent mirror costs."""
        r = _report()
        r["derived"]["price_action_lane"]["refusals"]["some_future_reason"] = 7
        r["derived"]["price_action_lane"]["refusal_share"]["some_future_reason"] = 0.0017
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "some_future_reason" in body
        assert "unclassified" in body

    def test_cooldown_is_not_pooled_with_the_market_refusals(self):
        """A cooldown means a setup WAS found and deliberately not stamped, so
        it is positive evidence the lane fires. Bucketing it with `no_sweep`
        would read as the market being quiet when it was us throttling."""
        from app.routes.data_intake import (
            LANE_REFUSAL_COPY,
            lane_class_totals,
            lane_refusal_rows,
        )
        rows = lane_refusal_rows(_report())
        totals = lane_class_totals(rows)
        assert LANE_REFUSAL_COPY["cooldown"][0] == "throttle"
        assert LANE_REFUSAL_COPY["no_sweep"][0] == "market"
        assert totals["throttle"]["count"] == 12
        assert "cooldown" not in [r["reason"] for r in rows if r["cls"] == "market"]

    def test_no_levels_is_a_fault_and_no_sweep_is_not(self):
        """The three states this card exists to separate have three different
        next moves; pooling them into "no signals" reports a fault that is not
        happening."""
        from app.routes.data_intake import LANE_REFUSAL_COPY
        assert LANE_REFUSAL_COPY["no_levels"][0] == "fault"
        assert LANE_REFUSAL_COPY["short_series"][0] == "fault"
        assert LANE_REFUSAL_COPY["no_footprint"][0] == "coverage"
        assert LANE_REFUSAL_COPY["no_sweep"][0] == "market"

    def test_a_missing_block_reads_as_an_old_engine_not_a_quiet_lane(self):
        """"Blank needs a cause before it gets a caption." An engine that never
        sent the block and a lane with nothing to say must not render alike —
        that conflation is the whole defect this card repairs."""
        r = _report()
        del r["derived"]["price_action_lane"]
        with _client(r) as c:
            body = c.get("/diagnostics/data-intake").text
        assert "NOT REPORTED" in body
        assert "not</strong> a lane with nothing to say" in body

    def test_the_rollup_is_computed_over_the_rows_the_table_shows(self):
        """#90: a summary over the whole ledger above a filtered table is not a
        summary of anything the reader is looking at."""
        from app.routes.data_intake import lane_class_totals, lane_refusal_rows
        rows = lane_refusal_rows(_report())
        totals = lane_class_totals(rows)
        assert sum(t["count"] for t in totals.values()) == sum(r["count"] for r in rows)
