"""Truth report — the age leads the page (2026-08-07).

This page rendered no timestamp at all while serving a TTL-cached snapshot of
the monitor-logs branch, so `cohort_edge_gate` read `streak 85` here and
`streak 156` on the live pulse for the same probe with nothing distinguishing
the clocks.
"""
from __future__ import annotations

from app.routes.truth import TRUTH_STALE_SEC, report_provenance

NOW = 1_786_073_747.0


class TestReportProvenance:
    def test_reads_the_engines_generated_at_not_ops_fetch_time(self):
        out = report_provenance(
            {"generated_at": NOW - 600, "lookback_hours": 24}, now_ts=NOW
        )
        assert out["age_sec"] == 600
        assert out["stale"] is False
        assert out["lookback_hours"] == 24
        assert out["generated_at_iso"].endswith("UTC")

    def test_an_old_report_is_stale(self):
        out = report_provenance({"generated_at": NOW - 6 * 3600}, now_ts=NOW)
        assert out["stale"] is True
        assert round(out["age_sec"] / 3600) == 6

    def test_the_bound_is_pinned(self):
        assert report_provenance(
            {"generated_at": NOW - TRUTH_STALE_SEC + 1}, now_ts=NOW)["stale"] is False
        assert report_provenance(
            {"generated_at": NOW - TRUTH_STALE_SEC - 1}, now_ts=NOW)["stale"] is True

    def test_missing_stamp_is_unknown_not_fresh(self):
        # A missing stamp is not a pass — `stale` stays None so the template
        # cannot render it as FRESH.
        for payload in ({}, {"generated_at": 0}, {"generated_at": "nope"},
                        {"error": "404"}, None):
            out = report_provenance(payload, now_ts=NOW)
            assert out["generated_at_iso"] is None
            assert out["stale"] is None
            assert out["age_sec"] is None


class TestTruthPageRendersItsAge:
    def _body(self, monkeypatch, snapshot):
        from fastapi.testclient import TestClient

        from app.main import app

        class _Logs:
            async def truth_snapshot(self):
                return snapshot

            async def window_comparison(self):
                return {}

            async def aclose(self):
                """Shutdown hook — the app closes its readers on teardown."""

        with TestClient(app) as client:
            app.state.monitor_logs = _Logs()
            client.post("/login", data={"password": "test-token"},
                        follow_redirects=False)
            return client.get("/truth").text

    def test_page_states_when_the_engine_generated_the_report(self, monkeypatch):
        import time

        body = self._body(monkeypatch, {
            "generated_at": time.time() - 300,
            "lookback_hours": 24,
            "executive_summary": {"overall_health": "healthy"},
        })
        assert "Generated by the engine at" in body
        assert "FRESH" in body
        assert "24h" in body

    def test_an_old_report_is_badged_stale_on_screen(self, monkeypatch):
        import time

        body = self._body(monkeypatch, {
            "generated_at": time.time() - 6 * 3600,
            "executive_summary": {"overall_health": "healthy"},
        })
        assert "STALE" in body
        assert "a window that has since moved on" in body

    def test_a_snapshot_with_no_stamp_says_unknown(self, monkeypatch):
        body = self._body(monkeypatch, {
            "executive_summary": {"overall_health": "healthy"},
        })
        assert "AGE UNKNOWN" in body
        assert "FRESH" not in body
